"""The firm's radio chatter.

HONESTY NOTE: in this phase the lines are *scripted templates* triggered by real events
in the simulation (a plan, a discovery, a finished building, low food...). The facts in
each line are live — who, what, where, how much — but the wording is not generated by a
model. When the LLM brain lands, agents will write these messages themselves and the
same channel carries them. The HUD labels the chat as scripted until then.
"""

from __future__ import annotations

import math
from collections import deque
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .sim import Simulation

COMPASS = ("east", "south-east", "south", "south-west", "west", "north-west", "north", "north-east")


def direction(x: float, z: float) -> str:
    if math.hypot(x, z) < 3:
        return "right by the camp"
    angle = math.atan2(z, x)  # +z is south on screen
    return "to the " + COMPASS[round(angle / (math.pi / 4)) % 8]


class Chatter:
    def __init__(self, sim: Simulation, scripted: bool = True):
        self.sim = sim
        self.scripted = scripted
        self.log: deque[dict] = deque(maxlen=120)
        self.pending: list[dict] = []
        self._queue: list[tuple[float, str, str, str | None]] = []
        self._id = 0
        self._cooldowns: dict[str, float] = {}

    # ── plumbing ──────────────────────────────────────────────────────────
    def _pick(self, *options: str) -> str:
        return self.sim.rng.choice(options)

    def say(self, speaker: str, text: str, to: str | None = None, delay: float = 0.0) -> None:
        """Queue a line; `delay` is in sim-seconds so replies arrive like a real exchange."""
        self._queue.append((self.sim.clock + delay, speaker, text, to))

    def _ready(self, key: str, every: float) -> bool:
        if self.sim.clock < self._cooldowns.get(key, -1e9):
            return False
        self._cooldowns[key] = self.sim.clock + every
        return True

    def update(self) -> None:
        due = [m for m in self._queue if m[0] <= self.sim.clock]
        if not due:
            return
        self._queue = [m for m in self._queue if m[0] > self.sim.clock]
        for _, speaker, text, to in sorted(due, key=lambda m: m[0]):
            self._id += 1
            msg = {"id": self._id, "day": self.sim.day, "time": self.sim.clock_string(), "from": speaker, "to": to, "text": text}
            self.log.append(msg)
            self.pending.append(msg)

    def name(self, agent_id: str) -> str:
        return self.sim.agent(agent_id).name

    # ── hooks called by the simulation ────────────────────────────────────
    def morning(self) -> None:
        if not self.scripted:
            return
        s = self.sim
        nxt = s.next_blueprint()
        plan = f"Next on the plan: the {s.blueprint_name(nxt)}." if nxt else "Every building on the plan is done."
        self.say("lina", f"Morning, team. Day {s.day}. We have {s.stock['wood']} wood, {s.stock['stone']} stone and {s.stock['food']} food. {plan}", "all")
        self.say("karim", self._pick("I'll be in the forest.", "Axe is sharp. Heading out for wood.", "Trees first, coffee later."), "all", 2.5)
        self.say("sara", self._pick("I'll keep the food coming.", "Berries and crops, as usual.", "Nobody goes hungry today."), "all", 4.5)

    def evening(self) -> None:
        if not self.scripted:
            return
        self.say("lina", self._pick("It's getting dark. Everyone back to camp.", "Sun's going down, let's call it a day.", "Night's coming. Head home, everyone."), "all")
        self.say("rayan", self._pick("On my way back.", "Coming, just finishing a lap.", "Heading in."), "lina", 2.0)
        if self._ready("night-yanis", 400):
            self.say("yanis", self._pick("Tomorrow we build more.", "My back hurts. Bed.", "Good day's work."), "all", 3.5)

    def planned(self, by: str, kind: str, tile_xz: tuple[float, float], cost: dict[str, int]) -> None:
        if not self.scripted:
            return
        s = self.sim
        where = direction(*tile_xz)
        need = " and ".join(f"{v} {k}" for k, v in cost.items())
        self.say(by, f"I've marked out a {s.blueprint_name(kind)} {where}. We need {need}.", "all")
        if "wood" in cost:
            self.say("yanis", f"Karim, can you bring wood for the {s.blueprint_name(kind)}?", "karim", 2.5)
            self.say("karim", self._pick("On it.", "Heading to the trees now.", "You'll have it soon."), "yanis", 4.5)
        if "stone" in cost:
            self.say("amine", self._pick("I'll handle the stone.", "Stone's on me.", "Leave the stone to me."), "all", 6.0)

    def construction_started(self, kind: str) -> None:
        if not self.scripted:
            return
        name = self.sim.blueprint_name(kind)
        self.say("yanis", self._pick(f"Materials are here. Starting on the {name}.", f"Everything's in. Building the {name} now.", f"Right, the {name}. Let's go."), "all")

    def completed(self, kind: str, by: str) -> None:
        if not self.scripted:
            return
        s = self.sim
        name = s.blueprint_name(kind)
        self.say(by, self._pick(f"The {name} is finished!", f"Done! The {name} is standing.", f"That's the {name} up."), "all")
        nxt = s.next_blueprint()
        if nxt:
            self.say("lina", f"Great work. Next up: the {s.blueprint_name(nxt)}.", "all", 2.5)
        if kind == "townhall":
            self.say("lina", "We did it. The camp is a city now.", "all", 5.0)

    def beds(self, names: list[str], kind: str) -> None:
        if not self.scripted:
            return
        if names:
            self.say("lina", f"{', '.join(names)}: you're sleeping in the new {self.sim.blueprint_name(kind)} tonight.", "all", 4.0)

    def discovered(self, by: str, biome: str, xz: tuple[float, float]) -> None:
        if not self.scripted:
            return
        where = direction(*xz)
        what = {"stone": "a rocky hill full of stone", "forest": "a pine forest", "water": "fresh water",
                "sand": "a sandy shore", "meadow": "wide open meadows"}.get(biome, biome)
        self.say(by, f"I found {what} {where}!", "all")
        reply = {
            "stone": ("amine", "Stone! That's where I'll be mining."),
            "forest": ("karim", "A forest? I'll be there with my axe."),
            "water": ("sara", "Fresh water nearby. Good spot for a farm."),
        }.get(biome)
        if reply:
            self.say(reply[0], reply[1], by, 2.5)

    def explored(self, share: int) -> None:
        if not self.scripted:
            return
        self.say("rayan", f"I've mapped {share}% of the island.", "all")

    def food_low(self) -> None:
        if not self.scripted:
            return
        if self._ready("food-low", 200):
            self.say("sara", f"Food is getting low: {self.sim.stock['food']} left in the crate. I'm going for berries.", "all")
            self.say("yanis", "Thanks Sara, I'm starving.", "sara", 2.5)

    def hungry(self, agent_id: str) -> None:
        if not self.scripted:
            return
        if self._ready(f"hungry-{agent_id}", 300):
            self.say(agent_id, self._pick("I need to eat something.", "Stomach's growling. Food break.", "Back in a minute, I need food."), "all")

    def tools(self, by: str) -> None:
        if not self.scripted:
            return
        self.say(by, "Stone tools are ready. Everyone gathers 50% faster now.", "all")
        self.say("karim", "Finally, a real axe!", by, 2.5)

    def harvested(self, amount: int) -> None:
        if not self.scripted:
            return
        self.say("sara", f"Harvested {amount} food from the farm.", "all")
        if self._ready("harvest-reply", 300):
            self.say("rayan", "Sara, you're the best.", "sara", 2.5)

    def ripe(self) -> None:
        if not self.scripted:
            return
        if self._ready("ripe", 120):
            self.say("sara", "The crop is ripe. Harvesting soon.", "all")

    # ── snapshot ──────────────────────────────────────────────────────────
    def drain(self) -> list[dict]:
        out, self.pending = self.pending, []
        return out
